# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\x12\x07predict\"a\n\x0ePredictRequest\x12\x13\n\x0bspeechiness\x18\x01 \x01(\x01\x12\x0e\n\x06\x65nergy\x18\x02 \x01(\x01\x12\x14\n\x0c\x64\x61nceability\x18\x03 \x01(\x01\x12\x14\n\x0c\x61\x63ousticness\x18\x04 \x01(\x01\"9\n\x0fPredictResponse\x12\x12\n\nint_output\x18\x01 \x01(\x08\x12\x12\n\nstr_output\x18\x02 \x01(\t2I\n\tPredictor\x12<\n\x07Predict\x12\x17.predict.PredictRequest\x1a\x18.predict.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PREDICTREQUEST']._serialized_start=26
  _globals['_PREDICTREQUEST']._serialized_end=123
  _globals['_PREDICTRESPONSE']._serialized_start=125
  _globals['_PREDICTRESPONSE']._serialized_end=182
  _globals['_PREDICTOR']._serialized_start=184
  _globals['_PREDICTOR']._serialized_end=257
# @@protoc_insertion_point(module_scope)
